Implement DeleteFile API
buildbuddy-io/buildbuddy pull request #2351
Opened 2022-07-29 18:47 UTC by maggie-lou

---

**Version bump**: TODO

2022-07-29 18:48 UTC, maggie-lou commented
Current dependencies on/for this PR:
* master
  * **PR #2349** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/2349" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #2350** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/2350" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #2351** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/2351" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/2351?utm_source=stack-comment).

2022-08-16 23:34 UTC, tylerwilliams requested changes
Delete API looks good, do you need to sync or something to resolve the flagtypes changes?

2022-08-16 23:34 UTC, tylerwilliams commented on enterprise/server/api/api_server.go
> +	enableCacheDeleteAPI = flag.Bool("enable_cache_delete_api", false, "If false, disable access to cache delete API.")
nit: If true, enable cache delete API?

2022-08-16 23:34 UTC, tylerwilliams commented on enterprise/server/api/api_server.go
> +		return nil, status.PermissionDeniedError("DeleteFile API not enabled for this user")
nit: DeleteFile API not enabled

(since it's not user-specific)

2022-08-16 23:34 UTC, tylerwilliams commented on enterprise/server/auth/auth.go
> +	oauthProviders       = flagtypes.Slice("auth.oauth_providers", []OauthProvider{}, "The list of oauth providers to use to authenticate.")
did you mean to have this diff in this CL?


(same with other flagtypes changes below)

2022-08-16 23:52 UTC, tylerwilliams requested changes

2022-08-16 23:52 UTC, tylerwilliams commented on enterprise/server/api/api_server_test.go
> +	"github.com/buildbuddy-io/buildbuddy/proto/api_key"
nit: can you move this up (with the other unnamed imports)

2022-08-23 18:49 UTC, tylerwilliams approved these changes

2022-08-23 21:53 UTC, merged