workflows: Have the CI runner fetch the main branch to support lint checks on changed files
buildbuddy-io/buildbuddy pull request #264
Opened 2021-03-11 18:52 UTC by bduffany

This is a small improvement to the CI runner: fetch the main branch in addition to just the branch that is being merged, so that lint checks can run `git merge-base HEAD refs/remotes/origin/master` to find the commit to compare against when running lint checks. Otherwise, lint checks would run on every file in the code base.

This shouldn't add much overhead for the git fetch, because the main branch and the PR branch should not have diverged a ton in most cases.

---

**Version bump**: Patch

2021-03-12 23:59 UTC, tylerwilliams requested changes
Code-wise this seems fine.

Complexity-wise -- I'm not totally in love with the idea of always checking out two branches just to make the linter faster. Is this commonly done in other ci-runners / are you sure this is something you think we should support long-term?

2021-03-16 19:40 UTC, bduffany commented
It's more than just for speed -- when you run `prettier` it prints out all the files in the repo that it checked making the logs huge and hard to visually parse -- it's nicer if it just shows the files that were added in the current PR.

2021-03-16 19:42 UTC, bduffany commented
I'm fine if we have better ideas on how to do per-merge lint checks properly in the long term, but I think this is a decent solution for now.

2021-03-17 18:39 UTC, tylerwilliams commented
Based on what you told me above, I think we should wait on this CL until we're further along and have a better feel for how folks use CI. It feels premature to change the default implementation that will affect everyone's builds just for our CI lint check needs. I understand and agree with you about why it's useful, but I'm worried about possible performance impact with large repos, and the inability to disable this. We can always add this feature on later, but if we launch with this it's much harder to take the feature away.

We can chat more about this if you want -- lmk!

2021-03-18 18:29 UTC, bduffany commented
SG! will close this for now.

2021-03-18 18:29 UTC, closed without merging