Support Command.output_paths
buildbuddy-io/buildbuddy pull request #2879
Opened 2022-11-08 18:16 UTC by iain-macdonald

This PR does a few things:
- Adds a more complex test for the various kinds of outputs (output_directories, output_files, and output_paths)
- Slightly changes the treatment of output_directories to match the description in the protocol here: https://github.com/bazelbuild/remote-apis/blob/main/build/bazel/remote/execution/v2/remote_execution.proto#L619 Specifically, before this change the executor would create all of the specified output_directories whereas now it will only create the parents of all of the specified output_directories. The behavior for output_files is unchanged.
- Uses output_paths instead of output_directories and output_files if specified, otherwise falls back to output_directories and output_files.

**Version bump**: Minor

Related issues: Fixes https://github.com/buildbuddy-io/buildbuddy-internal/issues/1766

2022-11-08 18:17 UTC, iain-macdonald commented
FYI I haven't yet managed to test this locally, still working on that. I'll let you know when I have.

2022-11-08 19:03 UTC, iain-macdonald commented
I managed to test this locally by changing this logic in Bazel: https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java#L233  I'll check with Siggi today to see if it works with his setup as well.

2022-11-09 01:02 UTC, iain-macdonald commented on dockerfiles/executor_image/Dockerfile
> +    apt-get update && apt-get -y upgrade && apt-get install -y podman=100:4.3.0-1 skopeo=100:1.10.0-1
Whoops, nope, gone now.

2022-11-09 01:32 UTC, iain-macdonald commented on enterprise/server/remote_execution/dirtools/dirtools.go
> +func (c *DirHelper) IsOutputPath(path string) bool {
Yup, done

2022-11-09 01:32 UTC, iain-macdonald commented on enterprise/server/test/integration/remote_execution/remote_execution_test.go
> +				// Make the output directory -- even though it's declared in
Done

2022-11-09 01:33 UTC, iain-macdonald commented on enterprise/server/test/integration/remote_execution/remote_execution_test.go
> +				// Make the output directory -- even though it's declared in
Looks like there is a tool that can do this automatically: https://github.com/segmentio/golines  I tried it and it works okay... support for comments is not so great. We could consider adding it to buildfix.

2022-11-09 01:33 UTC, iain-macdonald commented on enterprise/server/remote_execution/dirtools/dirtools.go
> +// output_path it is a descendent of and true, otherwise it returns an unspecified string and false.
Done

2022-11-09 01:44 UTC, tylerwilliams requested changes

2022-11-09 02:00 UTC, tylerwilliams approved these changes
LGTM

2022-11-09 02:01 UTC, iain-macdonald commented on enterprise/server/test/integration/remote_execution/remote_execution_test.go
> +    }
Whoops, yep

2022-11-09 02:18 UTC, merged