Use resource.ResourceName in distributed cache function
buildbuddy-io/buildbuddy pull request #2956
Opened 2022-11-18 23:37 UTC by maggie-lou

We need this change in order to pass a resource's compression type to distributed cache methods

2022-11-18 23:37 UTC, maggie-lou commented
Current dependencies on/for this PR:
* master
  * **PR #2838** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/2838" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #2932** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/2932" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #2956** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/2956" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/2956?utm_source=stack-comment).

2022-11-21 20:35 UTC, vadimberezniker requested changes
I don't think this change is backwards compatible / rollout safe.
We need to keep reading the isolation field in RPCs if the new resources field is not set.
This code is also deployed on on-prem installations so we should expect that we cannot remove the backwards compatibility handling until we properly notify customers.

2022-11-21 23:28 UTC, maggie-lou commented
> I don't think this change is backwards compatible / rollout safe. We need to keep reading the isolation field in RPCs if the new resources field is not set. This code is also deployed on on-prem installations so we should expect that we cannot remove the backwards compatibility handling until we properly notify customers.

Ah yes duh - my bad. Added some fallback code for that case

2022-11-28 21:28 UTC, vadimberezniker approved these changes

2022-11-28 23:48 UTC, merged