Add more migration logging to investigate eof error
buildbuddy-io/buildbuddy pull request #3124
Opened 2022-12-20 23:34 UTC by maggie-lou

---

**Version bump**: TODO

2022-12-20 23:34 UTC, maggie-lou commented
Current dependencies on/for this PR:
* master
  * **PR #3124** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/3124" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/3124?utm_source=stack-comment).

2022-12-20 23:39 UTC, vadimberezniker requested changes

2022-12-20 23:39 UTC, vadimberezniker commented on enterprise/server/backends/migration_cache/migration_cache.go
> +			d.bytesReadDest += dstN
bytesReadDest needs to be protected by a mutex since it's being read/written by multiple goroutines

2022-12-21 00:05 UTC, tylerwilliams approved these changes

2022-12-21 00:26 UTC, merged