Add logging for when GetEventLogChunk fails
buildbuddy-io/buildbuddy pull request #3197
Opened 2023-01-09 22:01 UTC by tempoz

This may give us insight into what's happening with log chunking and AWS.

---

**Version bump**: Patch

2023-01-09 22:02 UTC, tempoz commented
Current dependencies on/for this PR:
* master
  * **PR #3197** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/3197" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/3197?utm_source=stack-comment).

2023-01-09 22:06 UTC, vadimberezniker requested changes
Can you also add logging if the blobstore write fails when writing log chunks?

2023-01-09 22:06 UTC, vadimberezniker commented on enterprise/server/api/api_server.go
> +		log.Errorf("Encountered error getting event log chunk: %s\nRequest: %s", err, chunkReq.String())
nit: calling String() is redundant since %s calls the String() func automatically

2023-01-09 22:08 UTC, tylerwilliams commented on enterprise/server/api/api_server.go
> +		log.Errorf("Encountered error getting event log chunk: %s\nRequest: %s", err, chunkReq.String())
p sure you don't need to call .String() explicitly here -- it will be called for you to format your thing for %s. (Same below!)

2023-01-09 22:11 UTC, tempoz commented on enterprise/server/api/api_server.go
> +		log.Errorf("Encountered error getting event log chunk: %s\nRequest: %s", err, chunkReq.String())
```suggestion
		log.Errorf("Encountered error getting event log chunk: %s\nRequest: %s", err, chunkReq)
```

2023-01-09 22:11 UTC, tempoz commented on server/buildbuddy_server/buildbuddy_server.go
> +		log.Errorf("Encountered error getting event log chunk: %s\nRequest: %s", err, req.String())
```suggestion
		log.Errorf("Encountered error getting event log chunk: %s\nRequest: %s", err, req)
```

2023-01-09 22:57 UTC, vadimberezniker approved these changes

2023-01-10 01:09 UTC, tylerwilliams approved these changes

2023-01-10 16:04 UTC, merged