two digests at the same time
buildbuddy-io/buildbuddy pull request #3467
Opened 2023-02-24 23:18 UTC by tylerwilliams

- Support multiple digest functions
- Buildfix

2023-02-27 09:21 UTC, sluongng reviewed
The most exciting changes are in `server/remote_cache/digest/digest.go` and `server/remote_cache/byte_stream_server/byte_stream_server.go`. Everything else seems to be simple API migration.

Few nits but overall LGTM.

2023-02-27 09:21 UTC, sluongng commented on server/remote_cache/byte_stream_server/byte_stream_server.go
> +	if !digest.IsEmpty(r.GetDigest()) && !exists {
```suggestion
	if !digest.IsEmpty(r.GetDigest()) {
```

Nit: simplify. If exist, the function would have returned in the if clause above

2023-02-27 09:21 UTC, sluongng commented on server/remote_cache/byte_stream_server/byte_stream_server.go
> +	if !digest.IsEmpty(r.GetDigest()) && !exists {
then, it's probably easier to read if you flip the if/else so that we could remove the negation `!`

2023-02-27 18:57 UTC, tylerwilliams commented
PTAL

2023-02-27 23:56 UTC, vadimberezniker requested changes

2023-02-27 23:56 UTC, vadimberezniker commented on server/remote_cache/byte_stream_server/byte_stream_server.go
> +	if digest.IsEmpty(r.GetDigest()) {
It looks like you accidentally dropped the `exists` check.

2023-02-28 00:37 UTC, vadimberezniker approved these changes

2023-02-28 00:38 UTC, merged