Clean up snapshot manifest file IO
buildbuddy-io/buildbuddy pull request #3647
Opened 2023-03-24 20:57 UTC by bduffany

The snaploader accepts a workingDirectory param which it only uses to stage temporary files for copying to/from the filecache, and the loader impl has a decent amount of complexity around managing these temp files, which are only needed so that we can read/write bytes to/from the filecache.

This PR moves this complexity out of snaploader and into a new `filecacheutil` package, which should make the snaploader code a bit easier to work with.

---

**Version bump**: Patch

2023-03-24 21:41 UTC, maggie-lou approved these changes

2023-03-24 22:02 UTC, vadimberezniker requested changes

2023-03-27 16:28 UTC, vadimberezniker commented on enterprise/server/util/filecacheutil/filecacheutil.go
> +	if !fc.FastLinkFile(node, tmp) {
On *NIX systems, deleting a file does not invalidate file handles so if you already have a file handle there's no need to worry about the file being deleted. File data is not removed until all the file handles are closed. 

It's not a big deal so I'm fine with this approach if you want to stick with it.

2023-03-27 16:28 UTC, vadimberezniker approved these changes

2023-03-27 17:06 UTC, bduffany commented on enterprise/server/util/filecacheutil/filecacheutil.go
> +	if !fc.FastLinkFile(node, tmp) {
Ah, that's good to know. I'll stick with this for now since the current code avoids introducing another interface method.

2023-03-27 17:07 UTC, merged