Don't fail the release assets script if there are assets missing. Failing should be reserved if something actually breaks
buildbuddy-io/buildbuddy pull request #3725
Opened 2023-04-05 22:42 UTC by maggie-lou

---

**Version bump**: TODO

2023-04-05 22:42 UTC, maggie-lou commented
Current dependencies on/for this PR:
* master
  * **PR #3725** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/3725" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/3725?utm_source=stack-comment).

2023-04-06 00:25 UTC, iain-macdonald requested changes
What's the issue if it fails? Are there cases where it's okay for the assets to be missing?

2023-04-06 17:29 UTC, maggie-lou commented
> > What's the issue if it fails? Are there cases where it's okay for the assets to be missing?
> 
> +1, if the intention is to ignore the error and maybe send the stderr to slack, maybe it's clearer to explicitly handle the failing exit code in bash?

This week in the release, the script failed because the version tag interpolation failed. However I had script || true in the workflow, so it wasn't registered as a failure. We need a way to detect a difference between the script failing because of something unexpected vs the script detecting missing assets where we want to capture stderr and send to slack

2023-04-06 17:34 UTC, bduffany approved these changes

2023-04-06 17:36 UTC, merged