Ran `go mod tidy` now that the repos have been unified
buildbuddy-io/buildbuddy pull request #581
Opened 2021-06-22 16:50 UTC by tempoz

`go mod tidy` works now! Fixes some lingering problems with gopls not finding imports.

---

**Version bump**: Patch

2021-06-22 17:04 UTC, vadimberezniker requested changes
Nice!!

Can you sync the changes to `deps.bzl`?

2021-06-22 17:43 UTC, tempoz commented
Ah, right! forgot.

2021-06-22 22:03 UTC, tylerwilliams approved these changes
LGTM (assuming @vadimberezniker is happy with it)

2021-06-23 18:51 UTC, vadimberezniker approved these changes

2021-06-23 19:36 UTC, merged