Add blog post for debugging slow bazel builds
buildbuddy-io/buildbuddy pull request #6151
Opened 2024-03-14 18:22 UTC by maggie-lou

**Related issues**: N/A

2024-03-20 22:37 UTC, iain-macdonald requested changes
On one of my blog posts, Brandon recommended using webp images instead of pngs and that reduced the size significantly which is good for page load time and to reduce the size of our git repo. Would you mind converting the pngs to webps and overwriting the commit and force pushing so the pngs aren't in our repository too?

2024-03-20 22:37 UTC, iain-macdonald commented on website/blog/why-was-my-bazel-build-so-slow.md
> +
Mind throwing a `<!-- truncate -->` tag in here somewhere so only a snippet shows up in the blog homepage?

2024-03-20 22:37 UTC, iain-macdonald commented on website/blog/why-was-my-bazel-build-so-slow.md
> +Maybe you ran two builds and you’re surprised the second build ran so slowly, when you’d expected it to be cached. Or maybe you ran one build, and you just want to understand where all the time was s
More than "a couple" here :-)

2024-03-20 22:37 UTC, iain-macdonald commented on website/blog/why-was-my-bazel-build-so-slow.md
> +possible without it, it will be a lot more work to find and parse the info from Bazel yourself.
s/Bazel/build event stream ?

2024-03-20 22:37 UTC, iain-macdonald commented on website/blog/why-was-my-bazel-build-so-slow.md
> +  - This flag can improve execution throughput by allowing more actions to execute in parallel.
Could you mention our recommended value for this flag, if we have one?

2024-03-20 22:37 UTC, iain-macdonald commented on website/blog/why-was-my-bazel-build-so-slow.md
> +_The top invocation does not have –remote_download_minimal enabled, which could negatively impact performance._
Maybe worth recommending these are all set via a `.bazelrc` that's checked into git?

2024-03-20 22:37 UTC, iain-macdonald commented on website/blog/why-was-my-bazel-build-so-slow.md
> +⭐ If Bazel doesn’t have enough memory, it will evict parts of the analysis cache. As described in the previous section, this can significantly slow down builds. If you notice a lot of `MerkleTree.bui
Do we have a value we usually recommend, even if it's relative to the system properties? Or if not, maybe it's worth mentioning what the default is so it's obvious where to start?

2024-03-20 22:37 UTC, iain-macdonald commented on website/blog/why-was-my-bazel-build-so-slow.md
> +date: 2024-3-14 12:00:00
Mind updating the date when you merge?

2024-04-02 16:57 UTC, siggisim approved these changes

2024-04-02 18:05 UTC, merged