[Raft] Add a transaction janitor
buildbuddy-io/buildbuddy pull request #6374
Opened 2024-04-15 18:50 UTC by luluz66

**Related issues**: 
https://github.com/buildbuddy-io/buildbuddy-internal/issues/3279

- Add a proto `TxnRecord` and store it in meta range at different stages of
`RunTxn`. 
- Add a transaction janitor process to read the txn record and help get the
  stuck transactions unstuck.

2024-04-16 04:24 UTC, tylerwilliams requested changes
overall this looks good -- just a few comments!

2024-04-16 04:24 UTC, tylerwilliams commented on enterprise/server/raft/constants/constants.go
> +	TxnRecordPrefix = keys.MakeKey(SystemPrefix, []byte("txn-record-"))
nit: is it worth specifying that it's a coordinator record to distinguish from replica written value?

2024-04-16 04:24 UTC, tylerwilliams commented on enterprise/server/raft/rbuilder/rbuilder.go
> +		}
can you add this in a separate CL?

2024-04-16 04:24 UTC, tylerwilliams commented on enterprise/server/raft/txnjanitor/txnjanitor.go
> +type TxnJanitor struct {
we should add tests for this functionality

2024-04-23 21:05 UTC, tylerwilliams reviewed
it's kind of messy how DeleteTxnRecord and WriteTxnRecord are in the sender but called from the janitor. Could all of these txn coordinator methods be moved to a txncoordinator file, along with the janitor code?

2024-04-24 18:43 UTC, luluz66 commented
> it's kind of messy how DeleteTxnRecord and WriteTxnRecord are in the sender but called from the janitor. Could all of these txn coordinator methods be moved to a txncoordinator file, along with the janitor code?
I moved the txn related methods including RunTxn from sender to txn.go.

2024-04-24 21:27 UTC, tylerwilliams approved these changes

2024-04-24 21:27 UTC, tylerwilliams commented on enterprise/server/raft/txn/txn.go
> +type TxnCoordinator struct {
nit: just call this Coordinator

2024-04-24 21:51 UTC, merged