Fix race condition with executor shutdown
buildbuddy-io/buildbuddy pull request #747
Opened 2021-07-20 17:21 UTC by bduffany

---

**Version bump**: Patch

2021-07-20 17:30 UTC, tylerwilliams requested changes
LGTM but have @vadimberezniker give it a once over before submitting too please.

2021-07-20 17:30 UTC, tylerwilliams commented on enterprise/server/remote_execution/runner/runner.go
> +	errs := []error{}
errs := make([]error, 0)

2021-07-20 18:23 UTC, siggisim commented on enterprise/server/remote_execution/workspace/workspace.go
> +	WorkspaceMarkedForRemovalError = status.UnavailableError("workspace is marked for removal")
We should make sure these are retried

2021-07-20 18:23 UTC, vadimberezniker approved these changes
LGTM

2021-07-20 18:39 UTC, bduffany commented on enterprise/server/remote_execution/runner/runner.go
> +	errs := []error{}
Done

2021-07-20 22:59 UTC, bduffany commented on enterprise/server/remote_execution/workspace/workspace.go
> +	WorkspaceMarkedForRemovalError = status.UnavailableError("workspace is marked for removal")
Yep, unavailable errors are retried.

2021-07-20 23:03 UTC, bduffany commented
Tested this by running some local builds (~10 trials before and after) with a few artificial targets that generate a large amount of small output files, and having the executor send SIGTERM to itself right at the start of `workspace.UploadOutputs`.

With this test setup, before this change I was consistently seeing errors saying that certain outputs were expected, but not present. After the change, I was able to reliably build with no errors.

2021-07-21 01:23 UTC, tylerwilliams approved these changes
LGTM

2021-07-21 13:50 UTC, merged