Add flag to disable per test target Github status
buildbuddy-io/buildbuddy pull request #86
Opened 2020-10-03 09:47 UTC by purkhusid

## What?
Adds a new config variable that disables/enables the status-per-test-target funcitonality that exists now.

## Why?
When you have hundreds or thousands of test targets the status indicators become very hard to navigate. In this case it might make more sense for the end user to explore the whole invocation instead.

2020-10-03 09:49 UTC, purkhusid commented
I haven't had the chance to test this out on our setup because I'm getting cgo related errors when running the container.

I'm building the container on Fedora 32 and I get the following error:
`/app/server/cmd/buildbuddy: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /app/server/cmd/buildbuddy)`

2020-10-03 10:32 UTC, purkhusid commented
Manage to test this and this seems to work.

2020-10-03 20:15 UTC, tylerwilliams requested changes
Hey @purkhusid, thanks for the CL, this seems like it will be useful for big projects :) I had two minor nits but otherwise looks good to me.

2020-10-03 20:15 UTC, tylerwilliams commented on server/build_event_protocol/build_status_reporter/build_status_reporter.go
> +
Minor nit, but we should ensure that the GithubConfig is non-nil before using it. How about something like?

if githubConfig := r.env.GetConfigurator().GetGithubConfig(); githubConfig != nil {
  if githubConfig.shouldReportStatusPerTest != nil {
    return *githubConfig.shouldReportStatusPerTest
  }
}
return true

2020-10-03 20:15 UTC, tylerwilliams commented on server/build_event_protocol/build_status_reporter/build_status_reporter.go
> +	shouldReportStatusPerTest := r.shouldReportStatusPerTest()
What do you think about throwing a bool called "reportStatusPerTest" in the BuildStatusReporter struct and initializing it at BuildStatusReporter construction time? That way we're not having to re-reference the config file on every event.

2020-10-03 22:24 UTC, purkhusid commented
@tylerwilliams I addressed your comments!
You don't happen to have a solution for the glibc problem I mentioned above? I would love to have this change before you cut your next release but I can't build a functioning docker image.
You don't happen to publish docker images from the master branch?

2020-10-05 16:28 UTC, tylerwilliams commented
(Pinged you on slack to chat about the GLIBC issue)

2020-10-05 16:29 UTC, merged